package realtime.ods.hbasetable;

import org.apache.flink.addons.hbase.HBaseTableSource;
//import org.apache.flink.table.api.bridge.java.StreamTableEnvironment;
import org.apache.flink.table.api.java.StreamTableEnvironment;
import org.apache.hadoop.conf.Configuration;

/**
 * @author zy
 * @version 1.0
 * @description:
 * @date 2021/6/2 13:31
 */
public class DefineContractProductHbaseTable {
    public static void defineContractProduct(StreamTableEnvironment tableEnv, Configuration conf) {
        HBaseTableSource hBaseTableSource = new HBaseTableSource(conf, "t_contract_product");

        hBaseTableSource.setRowKey("item_id", String.class);
        hBaseTableSource.addColumn("f","master_id",String.class);
        hBaseTableSource.addColumn("f","policy_id",String.class);
        hBaseTableSource.addColumn("f","product_id",String.class);
        hBaseTableSource.addColumn("f","amount",String.class);
        hBaseTableSource.addColumn("f","unit",String.class);
        hBaseTableSource.addColumn("f","apply_date",String.class);
        hBaseTableSource.addColumn("f","expiry_date",String.class);
        hBaseTableSource.addColumn("f","validate_date",String.class);
        hBaseTableSource.addColumn("f","paidup_date",String.class);
        hBaseTableSource.addColumn("f","liability_state",String.class);
        hBaseTableSource.addColumn("f","end_cause",String.class);
        hBaseTableSource.addColumn("f","initial_type",String.class);
        hBaseTableSource.addColumn("f","renewal_type",String.class);
        hBaseTableSource.addColumn("f","charge_period",String.class);
        hBaseTableSource.addColumn("f","charge_year",String.class);
        hBaseTableSource.addColumn("f","coverage_period",String.class);
        hBaseTableSource.addColumn("f","coverage_year",String.class);
        hBaseTableSource.addColumn("f","short_end_time",String.class);
        hBaseTableSource.addColumn("f","except_value",String.class);
        hBaseTableSource.addColumn("f","benefit_level",String.class);
        hBaseTableSource.addColumn("f","insured_category",String.class);
        hBaseTableSource.addColumn("f","decision_id",String.class);
        hBaseTableSource.addColumn("f","suspend",String.class);
        hBaseTableSource.addColumn("f","suspend_cause",String.class);
        hBaseTableSource.addColumn("f","pay_mode",String.class);
        hBaseTableSource.addColumn("f","expiry_cash_value",String.class);
        hBaseTableSource.addColumn("f","count_way",String.class);
        hBaseTableSource.addColumn("f","renew_decision",String.class);
        hBaseTableSource.addColumn("f","bonus_sa",String.class);
        hBaseTableSource.addColumn("f","pay_next",String.class);
        hBaseTableSource.addColumn("f","origin_sa",String.class);
        hBaseTableSource.addColumn("f","origin_bonus_sa",String.class);
        hBaseTableSource.addColumn("f","anni_balance",String.class);
        hBaseTableSource.addColumn("f","fix_increment",String.class);
        hBaseTableSource.addColumn("f","cpf_cost",String.class);
        hBaseTableSource.addColumn("f","cash_cost",String.class);
        hBaseTableSource.addColumn("f","derivation",String.class);
        hBaseTableSource.addColumn("f","risk_code",String.class);
        hBaseTableSource.addColumn("f","exposure_rate",String.class);
        hBaseTableSource.addColumn("f","reins_rate",String.class);
        hBaseTableSource.addColumn("f","next_amount",String.class);
        hBaseTableSource.addColumn("f","waiver_start",String.class);
        hBaseTableSource.addColumn("f","waiver_end",String.class);
        hBaseTableSource.addColumn("f","auto_permnt_lapse",String.class);
        hBaseTableSource.addColumn("f","permnt_lapse_notice_date",String.class);
        hBaseTableSource.addColumn("f","master_product",String.class);
        hBaseTableSource.addColumn("f","waiver",String.class);
        hBaseTableSource.addColumn("f","waived_sa",String.class);
        hBaseTableSource.addColumn("f","issue_agent",String.class);
        hBaseTableSource.addColumn("f","strategy_code",String.class);
        hBaseTableSource.addColumn("f","loan_type",String.class);
        hBaseTableSource.addColumn("f","ben_period_type",String.class);
        hBaseTableSource.addColumn("f","benefit_period",String.class);
        hBaseTableSource.addColumn("f","gurnt_start_date",String.class);
        hBaseTableSource.addColumn("f","gurnt_perd_type",String.class);
        hBaseTableSource.addColumn("f","gurnt_period",String.class);
        hBaseTableSource.addColumn("f","invest_horizon",String.class);
        hBaseTableSource.addColumn("f","manual_sa",String.class);
        hBaseTableSource.addColumn("f","defer_period",String.class);
        hBaseTableSource.addColumn("f","sa_factor",String.class);
        hBaseTableSource.addColumn("f","std_prem_bf",String.class);
        hBaseTableSource.addColumn("f","discnt_prem_bf",String.class);
        hBaseTableSource.addColumn("f","discnted_prem_bf",String.class);
        hBaseTableSource.addColumn("f","policy_fee_bf",String.class);
        hBaseTableSource.addColumn("f","extra_prem_bf",String.class);
        hBaseTableSource.addColumn("f","std_prem_af",String.class);
        hBaseTableSource.addColumn("f","discnt_prem_af",String.class);
        hBaseTableSource.addColumn("f","policy_fee_af",String.class);
        hBaseTableSource.addColumn("f","gross_prem_af",String.class);
        hBaseTableSource.addColumn("f","extra_prem_af",String.class);
        hBaseTableSource.addColumn("f","total_prem_af",String.class);
        hBaseTableSource.addColumn("f","std_prem_an",String.class);
        hBaseTableSource.addColumn("f","discnt_prem_an",String.class);
        hBaseTableSource.addColumn("f","discnted_prem_an",String.class);
        hBaseTableSource.addColumn("f","policy_fee_an",String.class);
        hBaseTableSource.addColumn("f","extra_prem_an",String.class);
        hBaseTableSource.addColumn("f","next_std_prem_bf",String.class);
        hBaseTableSource.addColumn("f","next_discnt_prem_bf",String.class);
        hBaseTableSource.addColumn("f","next_discnted_prem_bf",String.class);
        hBaseTableSource.addColumn("f","next_policy_fee_bf",String.class);
        hBaseTableSource.addColumn("f","next_extra_prem_bf",String.class);
        hBaseTableSource.addColumn("f","next_std_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_discnt_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_discnted_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_policy_fee_af",String.class);
        hBaseTableSource.addColumn("f","next_gross_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_extra_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_total_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_std_prem_an",String.class);
        hBaseTableSource.addColumn("f","next_discnt_prem_an",String.class);
        hBaseTableSource.addColumn("f","next_discnted_prem_an",String.class);
        hBaseTableSource.addColumn("f","next_policy_fee_an",String.class);
        hBaseTableSource.addColumn("f","next_extra_prem_an",String.class);
        hBaseTableSource.addColumn("f","wait_period",String.class);
        hBaseTableSource.addColumn("f","waiv_anul_benefit",String.class);
        hBaseTableSource.addColumn("f","waiv_anul_prem",String.class);
        hBaseTableSource.addColumn("f","suspend_chg_id",String.class);
        hBaseTableSource.addColumn("f","lapse_cause",String.class);
        hBaseTableSource.addColumn("f","prem_change_time",String.class);
        hBaseTableSource.addColumn("f","submission_date",String.class);
        hBaseTableSource.addColumn("f","discnted_prem_af",String.class);
        hBaseTableSource.addColumn("f","policy_prem_source",String.class);
        hBaseTableSource.addColumn("f","ilp_calc_sa",String.class);
        hBaseTableSource.addColumn("f","actual_validate",String.class);
        hBaseTableSource.addColumn("f","entity_fund",String.class);
        hBaseTableSource.addColumn("f","car_reg_no",String.class);
        hBaseTableSource.addColumn("f","manu_surr_value",String.class);
        hBaseTableSource.addColumn("f","p_lapse_date",String.class);
        hBaseTableSource.addColumn("f","next_count_way",String.class);
        hBaseTableSource.addColumn("f","next_unit",String.class);
        hBaseTableSource.addColumn("f","initial_vali_date",String.class);
        hBaseTableSource.addColumn("f","age_increase_indi",String.class);
        hBaseTableSource.addColumn("f","paidup_option",String.class);
        hBaseTableSource.addColumn("f","last_statement_date",String.class);
        hBaseTableSource.addColumn("f","insur_prem_af",String.class);
        hBaseTableSource.addColumn("f","insur_prem_an",String.class);
        hBaseTableSource.addColumn("f","next_insur_prem_af",String.class);
        hBaseTableSource.addColumn("f","next_insur_prem_an",String.class);
        hBaseTableSource.addColumn("f","origin_product_id",String.class);
        hBaseTableSource.addColumn("f","car_reg_no_start",String.class);
        hBaseTableSource.addColumn("f","phd_period",String.class);
        hBaseTableSource.addColumn("f","pre_war_indi",String.class);
        hBaseTableSource.addColumn("f","waiver_claim_type",String.class);
        hBaseTableSource.addColumn("f","advantage_indi",String.class);
        hBaseTableSource.addColumn("f","issue_date",String.class);
        hBaseTableSource.addColumn("f","ri_processed",String.class);
        hBaseTableSource.addColumn("f","risk_commence_date",String.class);
        hBaseTableSource.addColumn("f","ems_version",String.class);
        hBaseTableSource.addColumn("f","inserted_by",String.class);
        hBaseTableSource.addColumn("f","updated_by",String.class);
        hBaseTableSource.addColumn("f","insert_time",String.class);
        hBaseTableSource.addColumn("f","update_time",String.class);
        hBaseTableSource.addColumn("f","insert_timestamp",String.class);
        hBaseTableSource.addColumn("f","update_timestamp",String.class);
        hBaseTableSource.addColumn("f","liability_state_cause",String.class);
        hBaseTableSource.addColumn("f","liability_state_date",String.class);
        hBaseTableSource.addColumn("f","invest_scheme",String.class);
        hBaseTableSource.addColumn("f","tariff_type",String.class);
        hBaseTableSource.addColumn("f","indx_suspend_cause",String.class);
        hBaseTableSource.addColumn("f","indx_type",String.class);
        hBaseTableSource.addColumn("f","indx_calc_basis",String.class);
        hBaseTableSource.addColumn("f","indx_indi",String.class);
        hBaseTableSource.addColumn("f","cooling_off_option",String.class);
        hBaseTableSource.addColumn("f","postpone_period",String.class);
        hBaseTableSource.addColumn("f","next_benefit_level",String.class);
        hBaseTableSource.addColumn("f","travel_type",String.class);
        hBaseTableSource.addColumn("f","free_object",String.class);
        hBaseTableSource.addColumn("f","ismortgage",String.class);
        hBaseTableSource.addColumn("f","end_cause_desc",String.class);
        hBaseTableSource.addColumn("f","ph_ag_rela",String.class);
        hBaseTableSource.addColumn("f","ph_ag_reladesc",String.class);
        hBaseTableSource.addColumn("f","over_fl_cause",String.class);
        hBaseTableSource.addColumn("f","over_fl_causedesc",String.class);
        hBaseTableSource.addColumn("f","real_lapse_date",String.class);
        hBaseTableSource.addColumn("f","next_due_date",String.class);
        hBaseTableSource.addColumn("f","next_due_prem",String.class);
        hBaseTableSource.addColumn("f","uw_decision",String.class);
        hBaseTableSource.addColumn("f","claim_amount",String.class);
        hBaseTableSource.addColumn("f","is_pledge",String.class);
        hBaseTableSource.addColumn("f","uw_decision_channel",String.class);
        hBaseTableSource.addColumn("f","all_add_amout",String.class);
        hBaseTableSource.addColumn("f","all_add_prem",String.class);



        tableEnv.registerFunction("t_lookup_item_id",hBaseTableSource.getLookupFunction(new String[]{"item_id"}));
    }
}
